# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_entry_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
